helmDefaults:
  wait: true
  timeout: 600

releases:
  - name: control-plane-jenkins
    namespace: '{{ env "NAMESPACE" }}'
    chart: ./
    labels:
      type: local
    values:
      - "values.yaml"
      - "values.gotmpl"
